echo Shutting off WSUS settings...
Set-ItemProperty -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU -Name UseWUServer -Value 0 ; Restart-Service wuauserv
echo Running install
DISM /Online /Enable-Feature /FeatureName:NetFx3 /All
echo All done...
