echo Shutting off WSUS settings...
Set-ItemProperty -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU -Name UseWUServer -Value 0 ; Restart-Service wuauserv
echo Running install
Get-WindowsCapability -Online | ? {$_.Name -match "Rsat"} | % {Add-WindowsCapability -Online -Name $_.Name}
echo All Done...
